#!/bin/bash

# settings for urxvt
xrdb -merge .Xresources
flock -n /tmp/urxvtd.lockfile urxvtd -q -o -f

# max redshift all the time
redshift -O 3700K

# use modifiers on their own as well
# mapping here mean
#  left ctrl -> left_alt + left_shift + o -> wor terminal
#  windows key -> alt+shift+u -> new terminal
#  right alt -> left_alt + left -> go to prev dwm tag
#  right ctrl -> left_alt + right -> go to next dwm tag
#  Print Screen -> left_alt + 8 -> go to 8th tag
#  right shift -> left_alt + tab -> go to previous tag
# left shift -> left_alt + j -> cycle in current tag
flock -n /tmp/xcape.lockfile xcape -e 'Control_L=Alt_L|Shift_L|o;Super_L=Alt_L|Shift_L|s;Control_R=Alt_L|Right;Alt_R=Alt_L|Left;Print=Alt_L|8;Shift_R=Alt_L|Tab;Shift_L=Alt_L|j'

# set the background
sh ~/.fehbg &

#flock -n /tmp/notificdaemon /usr/libexec/notification-daemon &

#flock -n /tmp/toplock.lockfile xdotool behave_screen_edge --delay 1000 top exec slock &
#flock -n /tmp/botlock.lockfile xdotool behave_screen_edge --delay 1000 bottom exec sleep-lock &

# cursor setting
export XCURSOR_THEME=bridge

# hide cursor when not really required
unclutter --timeout 1 --ignore-scrolling -b

exec dwm
